name: Nawah DevBot Deployment

on:
  push:
    branches:
      - devbot-kyc
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ استنساخ المستودع
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ إعداد بايثون
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3️⃣ تثبيت المكتبات المطلوبة
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ تشغيل سكربت النشر
      - name: Run deployment script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: ${{ secrets.RPC_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 scripts/deploy_contracts.py

      # 5️⃣ (اختياري) إرسال رسالة ترحيب/تأكيد في Telegram بعد النشر
      - name: Notify Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          python3 scripts/notify_telegram.py "Nawah DevBot deployment completed successfully!"

