name: Build & Deploy Nawah DevBot Pages

on:
  push:
    branches:
      - main  # الفرع الذي يتم النشر منه

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # إعداد Node.js إذا تحتاجه لموقع Pages
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install || echo "No dependencies to install"

      # رفع الملفات كمخزن Artifact
      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./pages

      # النشر على GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
